# Generated by Django 4.2.3 on 2023-07-22 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="BankCard",
            fields=[
                ("number", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, null=True)),
                ("exp_date", models.DateField()),
                ("cvv", models.IntegerField()),
                ("issue_date", models.DateField(auto_now_add=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="send_and_get_card.status",
                    ),
                ),
            ],
        ),
    ]
