# Generated by Django 4.2.3 on 2023-07-10 00:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('exp_date', models.DateField()),
                ('cvv', models.IntegerField()),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.UUID('cc602912-981d-40c9-a6ef-5c32e482234f'))),
                ('status', models.CharField(default='new', max_length=50)),
            ],
        ),
    ]
